name: "Setup Mono Repo"
description: "Setup tooling for mono repo"

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version-file: ".nvmrc"

    - uses: pnpm/action-setup@v4
    - run: |
        echo "DO_NOT_TRACK=1" >> $GITHUB_ENV
        echo "NEXT_TELEMETRY_DISABLED=1" >> $GITHUB_ENV
        echo "TURBO_TELEMETRY_DISABLED=1" >> $GITHUB_ENV
        pnpm install -g turbo
        pnpm install
      shell: bash
